copy /y maid_cog.py maidArturia\cogs
copy /y maid_cog.py maidAzusa\cogs
copy /y maid_cog.py maidMio\cogs
copy /y maid_cog.py maidmugi\cogs
copy /y maid_cog.py maidRam\cogs
copy /y maid_cog.py maidRem\cogs
copy /y maid_cog.py maidRitsu\cogs
copy /y maid_cog.py maidRumiho\cogs
copy /y maid_cog.py maidSaika\cogs
copy /y maid_cog.py maidYui\cogs

start /B python maidArturia/maid.py
start /B python maidAzusa/maid.py
start /B python maidMio/maid.py
start /B python maidmugi/maid.py
start /B python maidRam/maid.py
start /B python maidRem/maid.py
start /B python maidRitsu/maid.py
start /B python maidRumiho/maid.py
start /B python maidSaika/maid.py
start /B python maidYui/maid.py